### ISSUE TITLE
[FEA] Inference Support

### ISSUE THREAD

**Issue by benfred** [NVIDIA/NVTabular#475]
As part of the 0.4 Release, we need to add a solution for using NVTabular with inference servers like Triton or TF Serving

- [x] Evaluate the requirements for integration with Triton Inference Server and draft a plan for integration ( #476 )
- [x] POC Integration with Triton Inference Server ( #477 )
- [ ] POC Integration with TF Serving ( #186 )
- [x] Example notebooks ( #478 )
- [x] NVTabular Inference Container ( #479 )
- [ ] Benchmarking script for inference, integrated with nightly CI ( #480 )

**Comment by benfred** [comment]
The  benchmarking scripts will be done in 0.5, and the TF Serving POC will be done at an even later date - closing
