### ISSUE TITLE
[FEA] Reduce small-batch size inference overhead

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA/NVTabular#744]
- [x] Update operator API's to indicate what data representations they support, and allow configuring for use with inference (#918)
- [x] Update triton python model to use alternative 'dict' representations  (#921)
- [x] Provide optimized c++ versions of fill + categorify operators (#926)
